#!/usr/bin/env ruby

APP_PATH = File.join(File.dirname(__FILE__), '..')
ENV_PATH  = File.expand_path('../../config/environment',  __FILE__)
ENV['BUNDLE_GEMFILE'] = File.join(APP_PATH, 'Gemfile')

require ENV_PATH

Thread.abort_on_exception = true
Rails.logger = Logger.new $stdout
Rails.logger.sev_threshold = Logger::DEBUG

require 'converger'

Converger.start
