# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{lorenz}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew Rudenko"]
  s.date = %q{2010-10-24}
  s.description = %q{Lorenz}
  s.email = %q{ceo@prepor.ru}
  s.files = [
    ".document",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/lorenz.rb",
     "lib/lorenz/action.rb",
     "lib/lorenz/converge.rb",
     "lib/lorenz/delayed_action.rb",
     "lib/lorenz/diff.rb",
     "lib/lorenz/dsl.rb",
     "lib/lorenz/host.rb",
     "lib/lorenz/mixin/dsl_load.rb",
     "lib/lorenz/node.rb",
     "lib/lorenz/node/base.rb",
     "lib/lorenz/node/collector.rb",
     "lib/lorenz/node/cron.rb",
     "lib/lorenz/node/deploy.rb",
     "lib/lorenz/node/directory.rb",
     "lib/lorenz/node/execute.rb",
     "lib/lorenz/node/file.rb",
     "lib/lorenz/node/gem.rb",
     "lib/lorenz/node/git.rb",
     "lib/lorenz/node/ln.rb",
     "lib/lorenz/node/package.rb",
     "lib/lorenz/node/path.rb",
     "lib/lorenz/node/scm.rb",
     "lib/lorenz/node/service.rb",
     "lib/lorenz/node_dsl.rb",
     "lib/lorenz/node_list.rb",
     "lib/lorenz/recipe.rb",
     "lib/lorenz/recipe/meta_dsl.rb",
     "lib/lorenz/state.rb",
     "lib/lorenz/tasks.rb",
     "lib/lorenz/template.rb",
     "lib/lorenz/tools/state.rb",
     "lib/lorenz/tools/states_dsl.rb",
     "lib/lorenz/tools/transition.rb",
     "lib/lorenz/tools/versions_dsl.rb",
     "lib/lorenz/versions.rb",
     "lorenz.gemspec",
     "pkg/lorenz-0.0.1.gem",
     "spec/lorenz_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "test/states/common.rb",
     "test/test_helper.rb",
     "test/versions.rb"
  ]
  s.homepage = %q{http://github.com/prepor/lorenz}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Lorenz}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

