source 'http://rubygems.org'
source 'http://gems.undev.cc'

gem 'rails', '3.0.0'

gem 'ripple'
gem 'inherited_resources'

gem 'formtastic'
gem 'haml'
gem 'curb'
gem 'flutie'
gem 'open4'
gem 'state_machine'
gem 'eventmachine'
gem 'eventmachine_httpserver'
gem 'em-websocket'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'


# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
gem 'ruby-debug'
gem 'sinatra'
# gem 'thin'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:

group :development, :test do
  gem 'riak-client', :path => '../riak-client'
  gem 'lorenz', :path => '../lorenz'
end
